Add bookings
VladYXDP/java-shareit pull request #6
Opened 2024-07-24 09:58 UTC by VladYXDP

2024-07-25 14:42 UTC, db-exp requested changes

2024-07-25 14:42 UTC, db-exp commented on src/main/resources/schema.sql
> +    status     VARCHAR(255),
точно 255 не много?

2024-07-25 14:42 UTC, db-exp commented on src/main/resources/schema.sql
> +    text      VARCHAR(255),
лучше не назвывать поля как тип

2024-07-25 15:16 UTC, VladYXDP commented on src/main/java/ru/practicum/shareit/exceptions/ErrorHandler.java
> +    @ResponseStatus(HttpStatus.NOT_FOUND)
У них ведь разные статусы

2024-07-25 19:41 UTC, VladYXDP commented on src/main/java/ru/practicum/shareit/exceptions/ErrorHandler.java
> +    public Map<String, String> handleCreateBookingException(final CreateBookingException e) {
У них тоже разные статусы ведь

2024-07-25 20:48 UTC, VladYXDP commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +public class BookingServiceImpl implements BookingService {
В теории было затронуто, но не сильно. Проставлю над классами

2024-07-25 21:26 UTC, db-exp commented on src/main/java/ru/practicum/shareit/exceptions/ErrorHandler.java
> +    @ResponseStatus(HttpStatus.NOT_FOUND)
вижу NOT_FOUND на обоих

2024-07-25 21:26 UTC, db-exp commented on src/main/java/ru/practicum/shareit/exceptions/ErrorHandler.java
> +    public Map<String, String> handleCreateBookingException(final CreateBookingException e) {
@ResponseStatus(HttpStatus.NOT_FOUND)

2024-07-25 21:27 UTC, db-exp commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +public class BookingServiceImpl implements BookingService {
для методов чтения ставится Transactional(readOnly=true)

2024-07-26 15:23 UTC, VladYXDP commented on src/main/java/ru/practicum/shareit/exceptions/ErrorHandler.java
> +    @ResponseStatus(HttpStatus.NOT_FOUND)
Не понимаю. Если имеется ввиду CreateBookingException то это не AlreadyExists

2024-07-26 15:29 UTC, VladYXDP commented on src/main/java/ru/practicum/shareit/exceptions/ErrorHandler.java
> +    public Map<String, String> handleCreateBookingException(final CreateBookingException e) {
Не понимаю замечания. Сделано по тестам в одном Create 404 в другом 400 требуется

2024-07-28 08:06 UTC, db-exp approved these changes

2024-07-28 08:06 UTC, db-exp commented on src/main/java/ru/practicum/shareit/exceptions/ErrorHandler.java
> +    public Map<String, String> handleCreateBookingException(final CreateBookingException e) {
понял, меня выше смутили строки, извини

2024-07-28 13:30 UTC, merged